payload:

  # Download
  - DOMAIN,object.github.com
  - DOMAIN,dl.google.com
  - DOMAIN-SUFFIX,gvt1.com
  - DOMAIN,packages.chocolatey.org
  - DOMAIN,download.visualstudio.microsoft.com
  
  # Emby
  - DOMAIN,emby,aca.best
  - DOMAIN,porn.aca.best
  - DOMAIN-SUFFIX,imetyou.top
  
  # Video
  - DOMAIN-SUFFIX,googlevideo.com
  - DOMAIN-SUFFIX,ttvnw.net
